### ISSUE TITLE
How to handle pull refresh?

### ISSUE THREAD

**Issue by dioseltorre** [quantosapplications/riverpod_infinite_scroll#1]

**Comment by ftognetto** [comment]
Hi! Thank you for the question.

Right now, I'm handling pull to refresh with `ref.refresh(easyExampleProvider)` which, applied to a notifier that extends **PagedNotifier** will call load function with the initial page.

 In this way:

```
@override
  Widget build(BuildContext  context){
    return Scaffold(
      appBar: AppBar(),
      body: RefreshIndicator(
        onRefresh: () async { return ref.refresh(communityRecentsProvider); },
        child: RiverPagedBuilder<int, Post>(
          firstPageKey: 0,
          provider: easyExampleProvider,
          itemBuilder: (context, item, index) => ListTile(
            leading: Image.network(item.image),
            title: Text(item.title),
        ),
        pagedBuilder: (controller, builder) => PagedListView(pagingController: controller, builderDelegate: builder),
      ),
    );
  }
```

But It could be a good idea to integrate the RefreshIndicator directly into RiverPagedBuilder because it already know how to refresh the list. I will add this to the todo list, thanks!

**Comment by ftognetto** [comment]
Please have a look at this commit [d4d6ff0bb73b9f575afd31335d712893633299bf](https://github.com/quantosapplications/riverpod_infinite_scroll/commit/d4d6ff0bb73b9f575afd31335d712893633299bf)

It adds pull to refresh directly into RiverPagedBuilder

**Comment by dioseltorre** [comment]
Thanks for the quick response!
Looks great! When are you planning to release it?
Btw, it would be helpful if you could add the Github repo in pub.

**Comment by ftognetto** [comment]
Thanks to you! The version 1.0.2 is already on pub.dev, and I also added the GitHub repo.
Let me know if you find easy to use this package!

**Comment by dioseltorre** [comment]
Great job!
Yeah, it's super easy to use the package. It saves a lot of time thinking and implementing like this on my own😄
