### ISSUE TITLE
Make PagedState work as mixin?

### ISSUE THREAD

**Issue by h-unterp** [quantosapplications/riverpod_infinite_scroll#15]
it would be nice to be able to freeze the children of PagedState, however the only way to use inheritance with a @freezed is with a mixin. 

Eg: 

```dart
@freezed
class MyPageState extends PagedState with _$MyPageState
```

Currently, this is not possible because:
![Screen Shot 2022-07-02 at 2 44 43 AM](https://user-images.githubusercontent.com/772917/176989956-465cd030-976b-4045-81a1-574bf96407de.png)

Would you be ok if I make a PR to allow for this? If so, I will do it. 

Then the large .copyWith can be removed from the project.

**Comment by ftognetto** [comment]
I think we could add a new `PagedStateMixin` because `PagedState` is necessary to use the PagedNotifier in the "easy" way (the "easy" example).
If PagedState is a mixin then PagedNotifier could not use it as the state class.

If we use a mixin we could lead to an unopinionated way of using the package because the user should implement by hand all the properties of PagedState.
Maybe you find a clean way of do this if you can send me an example we could work on it!
