### ISSUE TITLE
How to make PagedListView stays where it was when leaving then navigating back from other screen?

### ISSUE THREAD

**Issue by vnnw** [quantosapplications/riverpod_infinite_scroll#30]
https://user-images.githubusercontent.com/4979571/202143481-b73d6d64-e762-4ab3-bab2-a682d22c2f35.mp4

First, thanks for sharing this repo.

I am new to flutter. I am wondering if it possible to make PagedListView stays where it was in case of leaving then navigating back from other screen?

As the video shows, I scrolled a few pages and left the screen then came back, and the screen show items 0 instead of where I was.

**Comment by swiftymf** [comment]
I don't think this is an issue with this package but rather preserving state between tabs. One way you can solve it is by building all your tabs within a TabViewController and then switching between them based on an index, for example. It looks like the way you have it set up the view is being built from scratch each time it appears which is why your list resets.
